name: "vulnmap code test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: khulnasoft-lab/actions/setup@master
      - name: Vulnmap Test
        run: vulnmap code test --org=${{ secrets.VULNMAP_ORG }} --sarif > vulnmap-sarif2.json
        continue-on-error: true
        env:
           VULNMAP_TOKEN: ${{ secrets.VULNMAP_TOKEN }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: vulnmap-sarif2.json
